AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  sam-app3

  Sample SAM Template for sam-app3
Globals:
  Function:
    Timeout: 365
    MemorySize: 512
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Layers:
      - !Ref SharedLayer
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
Resources:
  CreateAuthChallengeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CreateAuthChallenge/
      FunctionName: CreateAuthChallengeFunction
      Description: Lambda function to create an authentication challenge
      Handler: createAuthChallenge.handler
      Role: !GetAtt CognitoRoleForTriggers.Arn
      Events:
        CreateAuth:
          Type: Api
          Properties:
            Path: /create-auth-challenge
            Method: post
            RestApiId: !Ref TestApi
            Auth:
              Authorizer: TestCognitoUserPool
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:*
                Resource: "*"
    Metadata:
      External:
        - 'layer'
        - 'custom_util'

  DefineAuthChallengeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DefineAuthchallenge/
      FunctionName: DefineAuthChallengeFunction
      Description: Lambda function to define an authentication challenge
      Handler: defineAuthChallenge.handler
      Role: !GetAtt CognitoRoleForTriggers.Arn
      Events:
        DefineAuth:
          Type: Api
          Properties:
            Path: /define-auth-challenge
            Method: post
            RestApiId: !Ref TestApi
            Auth:
              Authorizer: TestCognitoUserPool
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:*
                Resource: "*"
    Metadata:
      External:
        - 'layer'
        - 'custom_util'

  VerifyAuthChallengeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: VerifyAuthchallenge/
      FunctionName: VerifyAuthChallengeFunction
      Description: Lambda function to verify an authentication challenge
      Handler: verifyAuthChallenge.handler
      Role: !GetAtt CognitoRoleForTriggers.Arn
      Events:
        VerifyAuthCh:
          Type: Api
          Properties:
            Path: /verify-auth-challenge
            Method: post
            RestApiId: !Ref TestApi
            Auth:
              Authorizer: TestCognitoUserPool
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:*
                Resource: "*"
    Metadata:
      External:
        - 'layer'
        - 'custom_util'

  AuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: auth-module/
      Handler: authModule.AuthLambdaHandler
      Role: !GetAtt CognitoRoleForTriggers.Arn
      Events:
        SignupEvent:
          Type: Api
          Properties:
            Path: /signup
            Method: post
            RestApiId: !Ref TestApi
        SigninEvent:
          Type: Api
          Properties:
            Path: /signin
            Method: post
            RestApiId: !Ref TestApi
            # Auth:
            #   Authorizer: TestCognitoUserPool
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:*
                Resource: "*"
    Metadata:
      External:
        - 'layer'
        - 'custom_util'

      #   SNSevent:
      #     Type: SNS
      #     Properties:
      #       Topic: !Ref CustomerOtpSNSTopic
      # Policies:
      #   - DynamoDBCrudPolicy:
      #       TableName: !Sub 'user-pre-signup-detail-${Env}'
      #   - DynamoDBReconfigurePolicy:
      #       TableName: !Sub 'user-pre-signup-detail-${Env}'
      #   - DynamoDBCrudPolicy:
      #       TableName: !Sub 'user-detail-${Env}'
      #   - DynamoDBReconfigurePolicy:
      #       TableName: !Sub 'user-detail-${Env}'

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLayer-auth-poc
      Description: Shared NPM package.
      ContentUri: 'layer/'
      CompatibleRuntimes:
        - nodejs18.x

  CognitoRoleForTriggers:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cognito-idp.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CognitoTriggersPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

  TestCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'test-userpool'
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      LambdaConfig:
        DefineAuthChallenge: !GetAtt DefineAuthChallengeFunction.Arn
        CreateAuthChallenge: !GetAtt CreateAuthChallengeFunction.Arn
        VerifyAuthChallengeResponse: !GetAtt VerifyAuthChallengeFunction.Arn
      AutoVerifiedAttributes: []
      Schema:
        - AttributeDataType: String
          Name: phone_number
  TestCognitoUserPoolCustomerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref TestCognitoUserPool
      Precedence: 0
      GroupName: 'customer'
  TestCognitoUserPoolAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      UserPoolId: !Ref TestCognitoUserPool
      Precedence: 1
      GroupName: 'admin'
  TestCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref TestCognitoUserPool
      ClientName: !Sub 'test-userpool-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  TestApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', ['/aws/apigateway/', !Sub '${AWS::StackName}', '/custom-log-group']]
      RetentionInDays: 365

  TestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          ThrottlingBurstLimit: 5000
          ThrottlingRateLimit: 3000.0
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          TestCognitoUserPool:
            UserPoolArn: !GetAtt TestCognitoUserPool.Arn
      AccessLogSetting:
        DestinationArn: !GetAtt TestApiLogGroup.Arn
        Format: '$context.requestId $context.identity.sourceIp $context.identity.caller $context.identity.user $context.httpMethod $context.resourcePath $context.status $context.responseLength $context.requestTime $context.protocol $context.responseLength $context.integrationErrorMessage'


Outputs:
  CreateAuthChallengeFunction:
    Description: Lambda Function ARN
    Value: !GetAtt CreateAuthChallengeFunction.Arn
